Repository QutEcoacoustics/baw-server, pull requests merged in 2020-07, with the labels that each got.

#476 PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#478 Basic shallow site routes
  .rubocop.yml
  app/controllers/sites_controller.rb
  config/routes.rb
  spec/acceptance/sites_spec.rb
Labels: API, enhancement

#481 By permission keyword arguments
  app/controllers/analysis_jobs_controller.rb
  app/controllers/audio_event_comments_controller.rb
  app/controllers/audio_events_controller.rb
  app/controllers/dataset_items_controller.rb
  app/controllers/progress_events_controller.rb
  app/controllers/projects_controller.rb
  app/controllers/public_controller.rb
  app/controllers/responses_controller.rb
  app/controllers/sites_controller.rb
  app/controllers/taggings_controller.rb
  app/modules/access/by_permission.rb
  app/modules/api/analysis_jobs_items_shared.rb
  spec/lib/modules/filter/query_spec.rb
  spec/models/analysis_jobs_item_spec.rb
Labels: architectural, enhancement

#479 Rswag - adds the ability to generate documentation for the API
  .github/workflows/ci.yml
  .rubocop.yml
  .vscode/launch.json
  Gemfile
  Gemfile.lock
  README.md
  app/models/project.rb
  baw-server.code-workspace
  bin/generate_docs.sh
  bin/rails
  config/initializers/rswag-ui.rb
  config/initializers/rswag_api.rb
  config/routes.rb
  lib/patches/rspec_api_documentation.rb
  spec/README.md
  spec/acceptance/projects_spec.rb
  spec/acceptance/public_spec.rb
  spec/api/projects_spec.rb
  spec/helpers/api_spec_helpers.rb
  spec/helpers/creation.rb
  spec/helpers/factory_bot_helpers.rb
  spec/helpers/permissions_helper.rb
  spec/helpers/request_spec_helpers.rb
  spec/rails_helper.rb
  spec/requests/permissions/README.md
  spec/requests/permissions/projects_public_spec.rb
  spec/requests/permissions/projects_spec.rb
  spec/requests/projects_spec.rb
  spec/requests/public_spec.rb
  spec/spec_helper.rb
  spec/swagger_helper.rb
  swagger/v1/swagger.yaml
Labels: API
